**Import Library**

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt

**Model**

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score

**Load DATA**

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [9]:
df = pd.read_csv("/content/drive/MyDrive/dataset/Descriptors.csv")
df

pIC50   ALogP    ALogp2      AMR       apol  naAromAtom  nAromBond  \
0    4.004892 -0.3240  0.104976  10.5451  27.871551           6          6   
1    3.420102  0.9086  0.825554  23.8407  30.298344           6          6   
2    3.468904  0.1557  0.024242  11.4176  27.761758           6          6   
3    3.806041  0.5648  0.318999  19.1442  30.254758           6          6   
4    4.070837  1.1646  1.356293  21.7763  30.897965           6          6   
..        ...     ...       ...      ...        ...         ...        ...   
102  5.044312  0.9828  0.965896  36.2771  53.522723          20         22   
103  4.274088  1.4208  2.018673  38.8217  54.249723          20         22   
104  6.677781  0.5810  0.337561  57.8307  66.428653          20         22   
105  4.486782  1.7271  2.982874  41.8927  55.035930          20         22   
106  4.922269  1.7271  2.982874  41.8927  55.035930          20         22   

     nAtom  nHeavyAtom  nH  ...        AMW     WTPT-1    WTPT-2     WTPT-3  \
0       21          14   7  ...   9.762845  28.229061  2.016362  11.016089   
1       23          15   8  ...   9.479460  30.087052  2.005803  11.017342   
2       21          15   6  ...  10.619539  30.087052  2.005803  13.537212   
3       21          15   6  ...  13.472870  30.087052  2.005803  13.537212   
4       21          16   5  ...  12.997229  31.934587  1.995912  16.074381   
..     ...         ...  ..  ...        ...        ...       ...        ...   
102     40          29  11  ...  10.625631  60.364692  2.081541  32.827381   
103     41          30  11  ...  10.927501  62.136726  2.071224  32.104003   
104     53          32  21  ...   8.813369  66.226728  2.069585  30.803251   
105     40          30  10  ...  11.474657  62.214397  2.073813  35.373455   
106     40          30  10  ...  11.474657  62.214397  2.073813  35.373455   

        WTPT-4     WTPT-5  WPATH  WPOL  XLogP  Zagreb  
0     5.042900   2.956971    314    16  2.925      70  
1     5.043334   2.957234    387    18  3.502      76  
2     5.043334   2.957234    387    18  1.829      76  
3     5.043334   2.957234    387    18  2.304      76  
4     5.042973   2.957015    448    21  2.062      82  
..         ...        ...    ...   ...    ...     ...  
102  10.576771  15.981493   2371    46  4.156     162  
103   5.738924  12.946934   2527    48  5.594     170  
104   8.315470  16.218559   3092    53  3.751     176  
105  10.576758  15.982096   2527    49  4.252     168  
106  10.576758  15.982096   2527    49  4.252     168  

[107 rows x 1043 columns]

In [10]:
print(df.columns)

Index(['pIC50', 'ALogP', 'ALogp2', 'AMR', 'apol', 'naAromAtom', 'nAromBond',
       'nAtom', 'nHeavyAtom', 'nH',
       ...
       'AMW', 'WTPT-1', 'WTPT-2', 'WTPT-3', 'WTPT-4', 'WTPT-5', 'WPATH',
       'WPOL', 'XLogP', 'Zagreb'],
      dtype='object', length=1043)


**Checking for Null Values**

In [11]:
df.isnull()

pIC50  ALogP  ALogp2    AMR   apol  naAromAtom  nAromBond  nAtom  \
0    False  False   False  False  False       False      False  False   
1    False  False   False  False  False       False      False  False   
2    False  False   False  False  False       False      False  False   
3    False  False   False  False  False       False      False  False   
4    False  False   False  False  False       False      False  False   
..     ...    ...     ...    ...    ...         ...        ...    ...   
102  False  False   False  False  False       False      False  False   
103  False  False   False  False  False       False      False  False   
104  False  False   False  False  False       False      False  False   
105  False  False   False  False  False       False      False  False   
106  False  False   False  False  False       False      False  False   

     nHeavyAtom     nH  ...    AMW  WTPT-1  WTPT-2  WTPT-3  WTPT-4  WTPT-5  \
0         False  False  ...  False   False   False   False   False   False   
1         False  False  ...  False   False   False   False   False   False   
2         False  False  ...  False   False   False   False   False   False   
3         False  False  ...  False   False   False   False   False   False   
4         False  False  ...  False   False   False   False   False   False   
..          ...    ...  ...    ...     ...     ...     ...     ...     ...   
102       False  False  ...  False   False   False   False   False   False   
103       False  False  ...  False   False   False   False   False   False   
104       False  False  ...  False   False   False   False   False   False   
105       False  False  ...  False   False   False   False   False   False   
106       False  False  ...  False   False   False   False   False   False   

     WPATH   WPOL  XLogP  Zagreb  
0    False  False  False   False  
1    False  False  False   False  
2    False  False  False   False  
3    False  False  False   False  
4    False  False  False   False  
..     ...    ...    ...     ...  
102  False  False  False   False  
103  False  False  False   False  
104  False  False  False   False  
105  False  False  False   False  
106  False  False  False   False  

[107 rows x 1043 columns]

In [12]:
df.isnull().sum()

pIC50     0
ALogP     0
ALogp2    0
AMR       0
apol      0
         ..
WTPT-5    0
WPATH     0
WPOL      0
XLogP     0
Zagreb    0
Length: 1043, dtype: int64

In [13]:
df.isnull().sum().sum()

4125

In [14]:
df2 = df.fillna(value = 0) 
df2

pIC50   ALogP    ALogp2      AMR       apol  naAromAtom  nAromBond  \
0    4.004892 -0.3240  0.104976  10.5451  27.871551           6          6   
1    3.420102  0.9086  0.825554  23.8407  30.298344           6          6   
2    3.468904  0.1557  0.024242  11.4176  27.761758           6          6   
3    3.806041  0.5648  0.318999  19.1442  30.254758           6          6   
4    4.070837  1.1646  1.356293  21.7763  30.897965           6          6   
..        ...     ...       ...      ...        ...         ...        ...   
102  5.044312  0.9828  0.965896  36.2771  53.522723          20         22   
103  4.274088  1.4208  2.018673  38.8217  54.249723          20         22   
104  6.677781  0.5810  0.337561  57.8307  66.428653          20         22   
105  4.486782  1.7271  2.982874  41.8927  55.035930          20         22   
106  4.922269  1.7271  2.982874  41.8927  55.035930          20         22   

     nAtom  nHeavyAtom  nH  ...        AMW     WTPT-1    WTPT-2     WTPT-3  \
0       21          14   7  ...   9.762845  28.229061  2.016362  11.016089   
1       23          15   8  ...   9.479460  30.087052  2.005803  11.017342   
2       21          15   6  ...  10.619539  30.087052  2.005803  13.537212   
3       21          15   6  ...  13.472870  30.087052  2.005803  13.537212   
4       21          16   5  ...  12.997229  31.934587  1.995912  16.074381   
..     ...         ...  ..  ...        ...        ...       ...        ...   
102     40          29  11  ...  10.625631  60.364692  2.081541  32.827381   
103     41          30  11  ...  10.927501  62.136726  2.071224  32.104003   
104     53          32  21  ...   8.813369  66.226728  2.069585  30.803251   
105     40          30  10  ...  11.474657  62.214397  2.073813  35.373455   
106     40          30  10  ...  11.474657  62.214397  2.073813  35.373455   

        WTPT-4     WTPT-5  WPATH  WPOL  XLogP  Zagreb  
0     5.042900   2.956971    314    16  2.925      70  
1     5.043334   2.957234    387    18  3.502      76  
2     5.043334   2.957234    387    18  1.829      76  
3     5.043334   2.957234    387    18  2.304      76  
4     5.042973   2.957015    448    21  2.062      82  
..         ...        ...    ...   ...    ...     ...  
102  10.576771  15.981493   2371    46  4.156     162  
103   5.738924  12.946934   2527    48  5.594     170  
104   8.315470  16.218559   3092    53  3.751     176  
105  10.576758  15.982096   2527    49  4.252     168  
106  10.576758  15.982096   2527    49  4.252     168  

[107 rows x 1043 columns]

In [15]:
df2.isnull().sum().sum()

0

**Input and Output Preparation**

In [16]:
X = df2.drop(['pIC50'],axis = 1)
X

ALogP    ALogp2      AMR       apol  naAromAtom  nAromBond  nAtom  \
0   -0.3240  0.104976  10.5451  27.871551           6          6     21   
1    0.9086  0.825554  23.8407  30.298344           6          6     23   
2    0.1557  0.024242  11.4176  27.761758           6          6     21   
3    0.5648  0.318999  19.1442  30.254758           6          6     21   
4    1.1646  1.356293  21.7763  30.897965           6          6     21   
..      ...       ...      ...        ...         ...        ...    ...   
102  0.9828  0.965896  36.2771  53.522723          20         22     40   
103  1.4208  2.018673  38.8217  54.249723          20         22     41   
104  0.5810  0.337561  57.8307  66.428653          20         22     53   
105  1.7271  2.982874  41.8927  55.035930          20         22     40   
106  1.7271  2.982874  41.8927  55.035930          20         22     40   

     nHeavyAtom  nH  nC  ...        AMW     WTPT-1    WTPT-2     WTPT-3  \
0            14   7  10  ...   9.762845  28.229061  2.016362  11.016089   
1            15   8  11  ...   9.479460  30.087052  2.005803  11.017342   
2            15   6  10  ...  10.619539  30.087052  2.005803  13.537212   
3            15   6  10  ...  13.472870  30.087052  2.005803  13.537212   
4            16   5  10  ...  12.997229  31.934587  1.995912  16.074381   
..          ...  ..  ..  ...        ...        ...       ...        ...   
102          29  11  18  ...  10.625631  60.364692  2.081541  32.827381   
103          30  11  19  ...  10.927501  62.136726  2.071224  32.104003   
104          32  21  22  ...   8.813369  66.226728  2.069585  30.803251   
105          30  10  18  ...  11.474657  62.214397  2.073813  35.373455   
106          30  10  18  ...  11.474657  62.214397  2.073813  35.373455   

        WTPT-4     WTPT-5  WPATH  WPOL  XLogP  Zagreb  
0     5.042900   2.956971    314    16  2.925      70  
1     5.043334   2.957234    387    18  3.502      76  
2     5.043334   2.957234    387    18  1.829      76  
3     5.043334   2.957234    387    18  2.304      76  
4     5.042973   2.957015    448    21  2.062      82  
..         ...        ...    ...   ...    ...     ...  
102  10.576771  15.981493   2371    46  4.156     162  
103   5.738924  12.946934   2527    48  5.594     170  
104   8.315470  16.218559   3092    53  3.751     176  
105  10.576758  15.982096   2527    49  4.252     168  
106  10.576758  15.982096   2527    49  4.252     168  

[107 rows x 1042 columns]

In [17]:
Y = df2.pIC50
Y

0      4.004892
1      3.420102
2      3.468904
3      3.806041
4      4.070837
         ...   
102    5.044312
103    4.274088
104    6.677781
105    4.486782
106    4.922269
Name: pIC50, Length: 107, dtype: float64

**Initiation of Recursive Feature Elimination (RFE) for Decision Tree Regressor**

In [18]:
gbr = GradientBoostingRegressor(random_state = 30)
sel = RFE(estimator=gbr, n_features_to_select=50)
sel.fit(X, Y)
sel.get_support()

array([False, False, False, ..., False, False, False])

In [19]:
len(sel.get_support())

1042

In [20]:
features = X.columns[sel.get_support()]

In [21]:
features

Index(['ATS0m', 'ATS6e', 'ATS7s', 'AATS7i', 'AATS6s', 'ATSC1v', 'ATSC4e',
       'ATSC6e', 'ATSC8p', 'ATSC8s', 'AATSC0c', 'AATSC7m', 'AATSC4v',
       'AATSC5e', 'AATSC5s', 'MATS1m', 'MATS2m', 'MATS4m', 'MATS1e', 'MATS7p',
       'GATS2c', 'GATS2m', 'GATS8e', 'GATS1p', 'GATS2p', 'GATS4i', 'VR3_Dzm',
       'VR3_Dzp', 'VE1_Dzi', 'SpAbs_Dzs', 'SpMax1_Bhv', 'SpMax1_Bhp',
       'SpMax6_Bhi', 'SpMin1_Bhi', 'SpMin2_Bhi', 'SpMin4_Bhs', 'CrippenMR',
       'minHCsats', 'minsOm', 'maxsCl', 'gmax', 'MAXDN2', 'DELS2', 'CIC3',
       'ZMIC0', 'ZMIC4', 'R_TpiPCTPC', 'VE2_D', 'WTPT-4', 'WTPT-5'],
      dtype='object')

In [22]:
len(features)

50

In [23]:
print(sel.ranking_)

[ 87  65 142 ... 989 992 993]


In [24]:
feature_importance = pd.DataFrame({"Feature_Name" : X.columns[sel.get_support()]})
feature_importance

Feature_Name
0         ATS0m
1         ATS6e
2         ATS7s
3        AATS7i
4        AATS6s
5        ATSC1v
6        ATSC4e
7        ATSC6e
8        ATSC8p
9        ATSC8s
10      AATSC0c
11      AATSC7m
12      AATSC4v
13      AATSC5e
14      AATSC5s
15       MATS1m
16       MATS2m
17       MATS4m
18       MATS1e
19       MATS7p
20       GATS2c
21       GATS2m
22       GATS8e
23       GATS1p
24       GATS2p
25       GATS4i
26      VR3_Dzm
27      VR3_Dzp
28      VE1_Dzi
29    SpAbs_Dzs
30   SpMax1_Bhv
31   SpMax1_Bhp
32   SpMax6_Bhi
33   SpMin1_Bhi
34   SpMin2_Bhi
35   SpMin4_Bhs
36    CrippenMR
37    minHCsats
38       minsOm
39       maxsCl
40         gmax
41       MAXDN2
42        DELS2
43         CIC3
44        ZMIC0
45        ZMIC4
46   R_TpiPCTPC
47        VE2_D
48       WTPT-4
49       WTPT-5

In [25]:
np.mean(sel.estimator_.feature_importances_)

0.02

In [26]:
sel.estimator_.feature_importances_

array([0.01091646, 0.0050044 , 0.00370736, 0.01978469, 0.02125845,
       0.00992966, 0.00242513, 0.00798899, 0.00387142, 0.00607923,
       0.0136332 , 0.00450388, 0.00592117, 0.00715759, 0.00582874,
       0.01683068, 0.0088638 , 0.02479732, 0.00208477, 0.0027394 ,
       0.00636833, 0.00472872, 0.01000058, 0.01267476, 0.00352836,
       0.00453914, 0.04996637, 0.01010913, 0.15384865, 0.0051993 ,
       0.06622654, 0.0070113 , 0.12302933, 0.00403108, 0.01095937,
       0.0954459 , 0.02715941, 0.09872936, 0.01900897, 0.00191241,
       0.00351335, 0.00275263, 0.00537116, 0.00445349, 0.04124999,
       0.01163228, 0.0173599 , 0.00299954, 0.00437489, 0.00848946])