**Import Library**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt

**Model**

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score

**Load DATA**

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
df = pd.read_csv("/content/drive/MyDrive/dataset/Descriptors.csv")
df

pIC50   ALogP    ALogp2      AMR       apol  naAromAtom  nAromBond  \
0    4.004892 -0.3240  0.104976  10.5451  27.871551           6          6   
1    3.420102  0.9086  0.825554  23.8407  30.298344           6          6   
2    3.468904  0.1557  0.024242  11.4176  27.761758           6          6   
3    3.806041  0.5648  0.318999  19.1442  30.254758           6          6   
4    4.070837  1.1646  1.356293  21.7763  30.897965           6          6   
..        ...     ...       ...      ...        ...         ...        ...   
102  5.044312  0.9828  0.965896  36.2771  53.522723          20         22   
103  4.274088  1.4208  2.018673  38.8217  54.249723          20         22   
104  6.677781  0.5810  0.337561  57.8307  66.428653          20         22   
105  4.486782  1.7271  2.982874  41.8927  55.035930          20         22   
106  4.922269  1.7271  2.982874  41.8927  55.035930          20         22   

     nAtom  nHeavyAtom  nH  ...        AMW     WTPT-1    WTPT-2     WTPT-3  \
0       21          14   7  ...   9.762845  28.229061  2.016362  11.016089   
1       23          15   8  ...   9.479460  30.087052  2.005803  11.017342   
2       21          15   6  ...  10.619539  30.087052  2.005803  13.537212   
3       21          15   6  ...  13.472870  30.087052  2.005803  13.537212   
4       21          16   5  ...  12.997229  31.934587  1.995912  16.074381   
..     ...         ...  ..  ...        ...        ...       ...        ...   
102     40          29  11  ...  10.625631  60.364692  2.081541  32.827381   
103     41          30  11  ...  10.927501  62.136726  2.071224  32.104003   
104     53          32  21  ...   8.813369  66.226728  2.069585  30.803251   
105     40          30  10  ...  11.474657  62.214397  2.073813  35.373455   
106     40          30  10  ...  11.474657  62.214397  2.073813  35.373455   

        WTPT-4     WTPT-5  WPATH  WPOL  XLogP  Zagreb  
0     5.042900   2.956971    314    16  2.925      70  
1     5.043334   2.957234    387    18  3.502      76  
2     5.043334   2.957234    387    18  1.829      76  
3     5.043334   2.957234    387    18  2.304      76  
4     5.042973   2.957015    448    21  2.062      82  
..         ...        ...    ...   ...    ...     ...  
102  10.576771  15.981493   2371    46  4.156     162  
103   5.738924  12.946934   2527    48  5.594     170  
104   8.315470  16.218559   3092    53  3.751     176  
105  10.576758  15.982096   2527    49  4.252     168  
106  10.576758  15.982096   2527    49  4.252     168  

[107 rows x 1043 columns]

In [5]:
print(df.columns)

Index(['pIC50', 'ALogP', 'ALogp2', 'AMR', 'apol', 'naAromAtom', 'nAromBond',
       'nAtom', 'nHeavyAtom', 'nH',
       ...
       'AMW', 'WTPT-1', 'WTPT-2', 'WTPT-3', 'WTPT-4', 'WTPT-5', 'WPATH',
       'WPOL', 'XLogP', 'Zagreb'],
      dtype='object', length=1043)


**Checking for Null Values**

In [6]:
df.isnull()

pIC50  ALogP  ALogp2    AMR   apol  naAromAtom  nAromBond  nAtom  \
0    False  False   False  False  False       False      False  False   
1    False  False   False  False  False       False      False  False   
2    False  False   False  False  False       False      False  False   
3    False  False   False  False  False       False      False  False   
4    False  False   False  False  False       False      False  False   
..     ...    ...     ...    ...    ...         ...        ...    ...   
102  False  False   False  False  False       False      False  False   
103  False  False   False  False  False       False      False  False   
104  False  False   False  False  False       False      False  False   
105  False  False   False  False  False       False      False  False   
106  False  False   False  False  False       False      False  False   

     nHeavyAtom     nH  ...    AMW  WTPT-1  WTPT-2  WTPT-3  WTPT-4  WTPT-5  \
0         False  False  ...  False   False   False   False   False   False   
1         False  False  ...  False   False   False   False   False   False   
2         False  False  ...  False   False   False   False   False   False   
3         False  False  ...  False   False   False   False   False   False   
4         False  False  ...  False   False   False   False   False   False   
..          ...    ...  ...    ...     ...     ...     ...     ...     ...   
102       False  False  ...  False   False   False   False   False   False   
103       False  False  ...  False   False   False   False   False   False   
104       False  False  ...  False   False   False   False   False   False   
105       False  False  ...  False   False   False   False   False   False   
106       False  False  ...  False   False   False   False   False   False   

     WPATH   WPOL  XLogP  Zagreb  
0    False  False  False   False  
1    False  False  False   False  
2    False  False  False   False  
3    False  False  False   False  
4    False  False  False   False  
..     ...    ...    ...     ...  
102  False  False  False   False  
103  False  False  False   False  
104  False  False  False   False  
105  False  False  False   False  
106  False  False  False   False  

[107 rows x 1043 columns]

In [7]:
df.isnull().sum()

pIC50     0
ALogP     0
ALogp2    0
AMR       0
apol      0
         ..
WTPT-5    0
WPATH     0
WPOL      0
XLogP     0
Zagreb    0
Length: 1043, dtype: int64

In [8]:
df.isnull().sum().sum()

4125

In [9]:
df2 = df.fillna(value = 0) 
df2

pIC50   ALogP    ALogp2      AMR       apol  naAromAtom  nAromBond  \
0    4.004892 -0.3240  0.104976  10.5451  27.871551           6          6   
1    3.420102  0.9086  0.825554  23.8407  30.298344           6          6   
2    3.468904  0.1557  0.024242  11.4176  27.761758           6          6   
3    3.806041  0.5648  0.318999  19.1442  30.254758           6          6   
4    4.070837  1.1646  1.356293  21.7763  30.897965           6          6   
..        ...     ...       ...      ...        ...         ...        ...   
102  5.044312  0.9828  0.965896  36.2771  53.522723          20         22   
103  4.274088  1.4208  2.018673  38.8217  54.249723          20         22   
104  6.677781  0.5810  0.337561  57.8307  66.428653          20         22   
105  4.486782  1.7271  2.982874  41.8927  55.035930          20         22   
106  4.922269  1.7271  2.982874  41.8927  55.035930          20         22   

     nAtom  nHeavyAtom  nH  ...        AMW     WTPT-1    WTPT-2     WTPT-3  \
0       21          14   7  ...   9.762845  28.229061  2.016362  11.016089   
1       23          15   8  ...   9.479460  30.087052  2.005803  11.017342   
2       21          15   6  ...  10.619539  30.087052  2.005803  13.537212   
3       21          15   6  ...  13.472870  30.087052  2.005803  13.537212   
4       21          16   5  ...  12.997229  31.934587  1.995912  16.074381   
..     ...         ...  ..  ...        ...        ...       ...        ...   
102     40          29  11  ...  10.625631  60.364692  2.081541  32.827381   
103     41          30  11  ...  10.927501  62.136726  2.071224  32.104003   
104     53          32  21  ...   8.813369  66.226728  2.069585  30.803251   
105     40          30  10  ...  11.474657  62.214397  2.073813  35.373455   
106     40          30  10  ...  11.474657  62.214397  2.073813  35.373455   

        WTPT-4     WTPT-5  WPATH  WPOL  XLogP  Zagreb  
0     5.042900   2.956971    314    16  2.925      70  
1     5.043334   2.957234    387    18  3.502      76  
2     5.043334   2.957234    387    18  1.829      76  
3     5.043334   2.957234    387    18  2.304      76  
4     5.042973   2.957015    448    21  2.062      82  
..         ...        ...    ...   ...    ...     ...  
102  10.576771  15.981493   2371    46  4.156     162  
103   5.738924  12.946934   2527    48  5.594     170  
104   8.315470  16.218559   3092    53  3.751     176  
105  10.576758  15.982096   2527    49  4.252     168  
106  10.576758  15.982096   2527    49  4.252     168  

[107 rows x 1043 columns]

In [10]:
df2.isnull().sum().sum()

0

**Input and Output Preparation**

In [11]:
X = df2.drop(['pIC50'],axis = 1)
X

ALogP    ALogp2      AMR       apol  naAromAtom  nAromBond  nAtom  \
0   -0.3240  0.104976  10.5451  27.871551           6          6     21   
1    0.9086  0.825554  23.8407  30.298344           6          6     23   
2    0.1557  0.024242  11.4176  27.761758           6          6     21   
3    0.5648  0.318999  19.1442  30.254758           6          6     21   
4    1.1646  1.356293  21.7763  30.897965           6          6     21   
..      ...       ...      ...        ...         ...        ...    ...   
102  0.9828  0.965896  36.2771  53.522723          20         22     40   
103  1.4208  2.018673  38.8217  54.249723          20         22     41   
104  0.5810  0.337561  57.8307  66.428653          20         22     53   
105  1.7271  2.982874  41.8927  55.035930          20         22     40   
106  1.7271  2.982874  41.8927  55.035930          20         22     40   

     nHeavyAtom  nH  nC  ...        AMW     WTPT-1    WTPT-2     WTPT-3  \
0            14   7  10  ...   9.762845  28.229061  2.016362  11.016089   
1            15   8  11  ...   9.479460  30.087052  2.005803  11.017342   
2            15   6  10  ...  10.619539  30.087052  2.005803  13.537212   
3            15   6  10  ...  13.472870  30.087052  2.005803  13.537212   
4            16   5  10  ...  12.997229  31.934587  1.995912  16.074381   
..          ...  ..  ..  ...        ...        ...       ...        ...   
102          29  11  18  ...  10.625631  60.364692  2.081541  32.827381   
103          30  11  19  ...  10.927501  62.136726  2.071224  32.104003   
104          32  21  22  ...   8.813369  66.226728  2.069585  30.803251   
105          30  10  18  ...  11.474657  62.214397  2.073813  35.373455   
106          30  10  18  ...  11.474657  62.214397  2.073813  35.373455   

        WTPT-4     WTPT-5  WPATH  WPOL  XLogP  Zagreb  
0     5.042900   2.956971    314    16  2.925      70  
1     5.043334   2.957234    387    18  3.502      76  
2     5.043334   2.957234    387    18  1.829      76  
3     5.043334   2.957234    387    18  2.304      76  
4     5.042973   2.957015    448    21  2.062      82  
..         ...        ...    ...   ...    ...     ...  
102  10.576771  15.981493   2371    46  4.156     162  
103   5.738924  12.946934   2527    48  5.594     170  
104   8.315470  16.218559   3092    53  3.751     176  
105  10.576758  15.982096   2527    49  4.252     168  
106  10.576758  15.982096   2527    49  4.252     168  

[107 rows x 1042 columns]

In [12]:
Y = df2.pIC50
Y

0      4.004892
1      3.420102
2      3.468904
3      3.806041
4      4.070837
         ...   
102    5.044312
103    4.274088
104    6.677781
105    4.486782
106    4.922269
Name: pIC50, Length: 107, dtype: float64

**Initiation of Recursive Feature Elimination (RFE) for Decision Tree Regressor**

In [13]:
dtr = DecisionTreeRegressor(random_state = 30)
sel = RFE(estimator=dtr, n_features_to_select=50)
sel.fit(X, Y)
sel.get_support()

array([False, False, False, ..., False, False, False])

In [14]:
len(sel.get_support())

1042

In [15]:
features = X.columns[sel.get_support()]

In [16]:
features

Index(['AATSC8c', 'AATSC0m', 'AATSC1m', 'AATSC2m', 'AATSC3m', 'AATSC4m',
       'AATSC5m', 'AATSC6m', 'AATSC7m', 'AATSC8m', 'AATSC0v', 'AATSC2v',
       'AATSC3v', 'AATSC4v', 'AATSC5v', 'AATSC7v', 'AATSC8v', 'AATSC2e',
       'AATSC4e', 'AATSC5e', 'AATSC6e', 'AATSC7e', 'AATSC8e', 'AATSC7p',
       'AATSC3i', 'MATS3c', 'GATS3c', 'GATS1p', 'VR2_DzZ', 'SM1_Dzp',
       'VR1_Dzp', 'SpMax7_Bhv', 'SpMax1_Bhe', 'SpMax6_Bhi', 'SsCl',
       'minHCsats', 'minHAvin', 'minHother', 'minsCH3', 'minssCH2', 'minaaCH',
       'mindssC', 'mindO', 'minssO', 'maxHBa', 'SIC2', 'CIC5', 'MDEC-13',
       'GGI8', 'VR1_D'],
      dtype='object')

In [17]:
len(features)

50

In [18]:
print(sel.ranking_)

[993 992 991 ... 756 862 865]


In [19]:
feature_importance = pd.DataFrame({"Feature_Name" : X.columns[sel.get_support()]})
feature_importance

Feature_Name
0       AATSC8c
1       AATSC0m
2       AATSC1m
3       AATSC2m
4       AATSC3m
5       AATSC4m
6       AATSC5m
7       AATSC6m
8       AATSC7m
9       AATSC8m
10      AATSC0v
11      AATSC2v
12      AATSC3v
13      AATSC4v
14      AATSC5v
15      AATSC7v
16      AATSC8v
17      AATSC2e
18      AATSC4e
19      AATSC5e
20      AATSC6e
21      AATSC7e
22      AATSC8e
23      AATSC7p
24      AATSC3i
25       MATS3c
26       GATS3c
27       GATS1p
28      VR2_DzZ
29      SM1_Dzp
30      VR1_Dzp
31   SpMax7_Bhv
32   SpMax1_Bhe
33   SpMax6_Bhi
34         SsCl
35    minHCsats
36     minHAvin
37    minHother
38      minsCH3
39     minssCH2
40      minaaCH
41      mindssC
42        mindO
43       minssO
44       maxHBa
45         SIC2
46         CIC5
47      MDEC-13
48         GGI8
49        VR1_D

In [20]:
np.mean(sel.estimator_.feature_importances_)

0.02

In [21]:
sel.estimator_.feature_importances_

array([1.18348365e-02, 5.03046428e-02, 7.13072487e-07, 8.90793410e-04,
       2.81691897e-06, 1.25910344e-05, 7.03893008e-04, 7.60443904e-04,
       1.50951882e-03, 2.17002309e-05, 0.00000000e+00, 7.09717194e-03,
       2.39642813e-04, 5.85480930e-06, 1.21719454e-03, 1.63931577e-06,
       1.53775992e-02, 2.06811477e-06, 3.01695902e-06, 2.81099647e-03,
       0.00000000e+00, 7.40615114e-05, 7.72709229e-03, 2.22521870e-04,
       1.05462575e-03, 1.38119117e-06, 1.00156736e-02, 4.88743257e-02,
       4.32194728e-03, 3.15340453e-03, 8.03182253e-02, 1.10846849e-03,
       5.92246139e-02, 3.88413360e-01, 1.84758019e-02, 1.63089300e-01,
       0.00000000e+00, 1.42577988e-05, 0.00000000e+00, 1.09684806e-04,
       1.17511750e-05, 6.75814779e-04, 8.87414482e-04, 0.00000000e+00,
       9.57535686e-03, 3.00329112e-04, 8.15092031e-02, 2.65391019e-04,
       2.08945312e-02, 6.88432867e-03])